theme: jekyll-theme-minimal
logo: chicago-ygl-logo.png
title: Chicago Young Government Leaders
description: Young Government Leader’s mission is to educate, inspire, and transform the current and future leaders of government. 
