title: Chicago Young Government Leaders
theme: jekyll-theme-minimal
logo: chicago-ygl-logo.jpg
description: Young Government Leader’s mission is to educate, inspire, and transform the current and future leaders of government. 
